In [15]:
import sqlite3
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

In [16]:
xlsx_path = Path(Path.cwd().parent) / "db/raw_data/test_data.xlsx"
xlsx_path

PosixPath('/home/jovyan/work/db/raw_data/test_data.xlsx')

In [17]:
df_2026 = pd.read_excel(xlsx_path, sheet_name=1)
df_2025 = pd.read_excel(xlsx_path, sheet_name=2)
df_total = pd.read_excel(xlsx_path, sheet_name=3)

In [18]:
df_2025.head()

,Учетный день,Номер чека,Время открытия,Час открытия,Время закрытия,Час закрытия,Блюдо,Категория блюда,Тип заказа,Количество блюд,Количество гостей,"Сумма со скидкой, р."
0,2025-02-01,12590,2025-02-01 10:06:50,10,2025-02-01 10:19:04,10,Д.Сырники с клубничным вареньем +,Д.ЗАВТРАКИ,Яндекс.ультима,2.0,2,1183.2
1,2025-02-01,12590,2025-02-01 10:06:50,10,2025-02-01 10:19:04,10,Д.Тёплый римский сэндвич +,Д.ЗАВТРАКИ,Яндекс.ультима,1.0,2,421.6
2,2025-02-01,12590,2025-02-01 10:06:50,10,2025-02-01 10:19:04,10,клубника (30 г),МОДИФИКАТОРЫ,Яндекс.ультима,1.0,2,156.4
3,2025-02-01,12591,2025-02-01 10:17:40,10,2025-02-01 10:39:13,10,Д.Бенедикт с лососем на круассане +,Д.ЗАВТРАКИ,Яндекс.ультима,1.0,2,952.0
4,2025-02-01,12591,2025-02-01 10:17:40,10,2025-02-01 10:39:13,10,Д.Драник с лососем и яйцом +,Д.ЗАВТРАКИ,Яндекс.ультима,1.0,2,673.2

In [19]:
df_2025.dtypes

Учетный день            datetime64[us]
Номер чека                       int64
Время открытия          datetime64[us]
Час открытия                     int64
Время закрытия          datetime64[us]
Час закрытия                     int64
Блюдо                              str
Категория блюда                    str
Тип заказа                         str
Количество блюд                float64
Количество гостей                int64
Сумма со скидкой, р.           float64
dtype: object

In [20]:
df_2026.head()

,Учетный день,Номер чека,Время открытия,Час открытия,Время закрытия,Час закрытия,Блюдо,Категория блюда,Тип заказа,Количество блюд,Количество гостей,"Сумма со скидкой, р."
0,2026-02-01,39551,2026-02-01 09:02:23,9,2026-02-01 10:02:53.685,10,Д.NEW Английский завтрак,Д.ЗАВТРАКИ,Приложение (доставка курьером),1.0,1,841.5
1,2026-02-01,39551,2026-02-01 09:02:23,9,2026-02-01 10:02:53.685,10,Д.Овсяная каша с бананом и голубикой,Д.ЗАВТРАКИ,Приложение (доставка курьером),1.0,1,382.5
2,2026-02-01,39551,2026-02-01 09:02:23,9,2026-02-01 10:02:53.685,10,Д.Салат Табуле,Д.ЗАВТРАКИ,Приложение (доставка курьером),1.0,1,518.5
3,2026-02-01,39551,2026-02-01 09:02:23,9,2026-02-01 10:02:53.685,10,Д.Тёплый римский сэндвич,Д.ЗАВТРАКИ,Приложение (доставка курьером),1.0,1,603.5
4,2026-02-01,39551,2026-02-01 09:02:23,9,2026-02-01 10:02:53.685,10,обычное,МОДИФИКАТОРЫ,Приложение (доставка курьером),1.0,1,0.0

In [21]:
df_2026.dtypes

Учетный день            datetime64[us]
Номер чека                       int64
Время открытия          datetime64[us]
Час открытия                     int64
Время закрытия          datetime64[us]
Час закрытия                     int64
Блюдо                              str
Категория блюда                    str
Тип заказа                         str
Количество блюд                float64
Количество гостей                int64
Сумма со скидкой, р.           float64
dtype: object

In [22]:
df_total.head()

,Учетный день,План на день,Ресторан,БАНКЕТ НАШ,Банкет C&B,Агрегатор,Самовывоз,Доставка
0,2026-02-01,945610.236397,621234.650671,71048.401550,33979.670306,126349.480927,27899.409883,65098.623060
1,2026-02-02,571575.604657,375506.268253,42945.318814,20539.065520,76372.143806,16863.842479,39348.965785
2,2026-02-03,705795.641717,463684.393475,53029.937954,25362.144239,94306.205177,20823.888262,48589.072611
3,2026-02-04,688107.641717,452063.962479,51700.950515,24726.541550,91942.789964,20302.019163,47371.378046
4,2026-02-05,924324.908967,607250.894530,69449.129004,33214.800828,123505.402078,27271.404758,63633.277769

In [23]:
df_total.dtypes

Учетный день    datetime64[us]
План на день           float64
Ресторан               float64
БАНКЕТ НАШ             float64
Банкет C&B             float64
Агрегатор              float64
Самовывоз              float64
Доставка               float64
dtype: object